version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qq04ikd4uupg"
s3_prefix = "resume-app"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
