AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create DB!

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Site_ViewCount"
      #TableName: "site_hit"
      AttributeDefinitions: 
        -
          AttributeName: "URL"
          AttributeType: "S"

      KeySchema: 
        -
          AttributeName: "URL"
          KeyType: "HASH"

      BillingMode: "PAY_PER_REQUEST"

  SiteCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        SiteGetViewCount:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayCount
            Path: /count
            Method: get

  ApiGatewayCount:
    Type: AWS::Serverless::Api
    Properties:
      Name: sitegetviewcount
      StageName: PROD
      EndpointConfiguration: Regional
    Cors: 
      AllowMethods: 'GET, OPTION'
      AllowHeaders: 'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'
      AllowOrigin: '*'