# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Python 3.8
        uses: actions/setup-python@v2
        with:
          python-verison: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install Boto
        run: |
          pip install boto3

      - name: Install moto
        run: |
          pip install moto

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: us-west-1

      - name: Use tests with unit test in py
        run: |
          ls
          cd Backend
          cd Lambda/
          ls
          python counter_test.py
          cd .
          Ls
          cd SAM
        - name: SAM Build Setting 
        use: youyo/aws-sam-action/python3.8/master
        with:
          sam_command: 'deploy --stack-name pyth38-test --no-fail-on-empty-changeset --resolve-s3 --capabilities CAPABILITY_NAMED_IAM'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1